dataset_id: "d-basic-scene"
model_id: "llava-v1.5-7b"
log_file: "./logs/truthfulness/basic-scene.json"
generation_kwargs: {
    'max_new_tokens': 512,
    'do_sample': False,
}

evaluator_seq_cfgs:
  [
    {
      "rule_yes_or_no_eval":
        {
          metrics_cfg:
            {
              pred_no_op: {}, accuracy_score: {}
            }
        },
    },
  ]