dataset_id: "advglue-plus-text"
model_id: "cogvlm-chat-hf"
log_file: "./logs/robustness/adversarial-text-advglue-text.json"

generation_kwargs: {
    'max_new_tokens': 200,
    'do_sample': False,
}

dataset_cfg: 
  generate_image: false

evaluator_seq_cfgs:
  [
    {
      "rule_contain_adv_eval":
        { metrics_cfg: { pred_mean: {} } },
    },
  ]
