dataset_id: "crossmodal-jailbreak-pos"
model_id: "llava-v1.5-7b"
log_file: "./logs/safety/crossmodal-jailbreak-pos.json"
generation_kwargs: {
  'max_new_tokens': 512,
  'do_sample': False,
  }
  

evaluator_seq_cfgs:
  [
    {
      "harmbenchmodel_eval":
        { metrics_cfg: { pred_no_op: {}, pred_mean: {} }}
    },
    {
      "rule_reject_template_eval":
        { metrics_cfg: { pred_no_op: {}, pred_mean: {} }}
    }
  ]
