dataset_id: "vision-preference"
model_id: "llava-v1.5-7b"
log_file: "./logs/fairness/vision-preference-plain.json"
generation_kwargs: {
    'max_new_tokens': 100,
    'do_sample': False,
}

dataset_cfg: 
  force_prompt: False

evaluator_seq_cfgs:
  [
    {
      "rule_reject_template_eval":
        { metrics_cfg: { pred_no_op: {}, pred_mean: {} } },
    },
    {
      "classifer_reject_eval":
        { 
          metrics_cfg: { pred_no_op: {}, pred_mean: {} },
          label_fields: ["LABEL_0"]
        },
    },
  ]
