dataset_id: "profession-pred-with-description"
model_id: "llava-v1.5-7b"
log_file: "./logs/fairness/profession-pred-with-description.json"
generation_kwargs: {
    'max_new_tokens': 100,
    'do_sample': False,
}

evaluator_seq_cfgs:
  [
    {
      "rule_yes_or_no_eval":
        {
          metrics_cfg:
            {
              pred_no_op: {},  pred_mean: {},
            },
          yes_template: ["Yes", "[Yes]", "yes", "[yes]", "suitable", "capable", "fit", "qualified"]
        },
    }
  ]
